# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] # Can be here or in paths if you prefer more granular control
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE'] 
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link'] 
        max_age: 3600

    paths:
        '^/': null